<?php
$online = TRUE; //True if running on godday server.
if ($online){
    require_once('/home/content/87/9635087/html/wp-load.php'); //GANs online
    $path ='/home/content/87/9635087/html/php-exec/ls/xml/'; //GANS online
    include_once '/home/content/87/9635087/html/php-exec/strip.php';
}
else{
    $path ='/home/kirk/http/feeds/php/LSall/xml/';
    include_once 'strip.php'; 
}

//Save file path is needed
include_once 'titleshorten.php';
include_once 'offerid.php';

include_once 'metadescleng.php';
include_once 'fnmapCat.php';
//include_once 'getVender.php'; Not needed using stock icons from LinkShare with xml file.  
$pagenumber=1;
$filePage = 'in/LSpageZ1.xml'; //file page 1
$fileOut ='out/LSoutZ.xml';//final file
$fileIDs ='in/IDs.xml'; //list of IDs to website
$token = "06a400a42d5ee2822cc4342b7cedf714bffa542768b1c06d571c0ebe8aa85203";  //zuuzlo - 06a400a42d5ee2822cc4342b7cedf714bffa542768b1c06d571c0ebe8aa85203, simple-coupons.com -e1b43458f742b15f89715dd8824a1c6ce3bb328f12624c34f3c08eb2de4ad007
//Find Ids in Existing file so we don't have to send them to website
/*$xmlid = new DOMDocument;
$xmlid->Load($path.$fileIDs);
$xid = $xmlid->documentElement;
$ids = $xid->getElementsByTagName('num');
$idlist = array();
foreach($ids as $idele){
   
    $idlist[] = $idele->nodeValue;
    
}*/
//put icons in array with key to be vender ID using the xml file generated by the getImage.php file
$imgfileOut ='out/LSImageoutZ.xml';//final file to SC
$xml = new DOMDocument('1.0', 'UTF-8');
$xml->Load($path.$imgfileOut);
$ximg = $xml->documentElement;
$vends = $ximg->getElementsByTagName('vends');
$imglist = array();
foreach($vends as $vend){
    $id = $vend->getElementsByTagName('vendid')->item(0)->nodeValue;
    $imglist[$id] = $vend->getElementsByTagName('imgurl')->item(0)->nodeValue;
}

//do loop to get the multiple pages if required.  Will write page1 then add all the other pages to this page
do{
$url = "http://couponfeed.linksynergy.com/coupon?token=$token&network=1&resultsperpage=500&pagenumber=$pagenumber";//mid=3184|13565 promotiontype=1|5|11|3|14&
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, FAlSE);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);

curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
//curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: '.$CJ_ID));
$curl_results = curl_exec($ch);
curl_close($ch);

$xml = new SimpleXMLElement($curl_results);
//determine number of pages
$element = $xml->TotalPages;
$pages = $element;
echo $pagenumber."<br />".$pages."<br />";

foreach($xml->link as $x){
	$vender = $x->{'advertiserid'};
	
//add coupon id
$cid = _couponid($x->{'clickurl'}, $x->{'advertiserid'});
//$cid = $cid."";
$x->addChild('id', $cid);

/*This code is intendend to remove items that have been sent to the website already.  
 * if(in_array($cid, $idlist)){
    $node = dom_import_simplexml($x);
    $node->parentNode->removeChild($node); 
    //unset($x);
}
else{
    $idlist[]= $cid;
    $elm = $xmlid->createElement('num',$cid);
    $xid->appendChild($elm);
}*/



//change buy.com to Rakuten. 		
if($x->{'advertiserid'} == '36342'){
    $x->{'advertisername'} = 'Rakuten.com';
    echo $x->{'advertisername'}.'<br>';
}
//Get rid of ongoing in end date just leave blank
if($x->{'offerenddate'} == 'ongoing'){
    $x->{'offerenddate'} = '';
}


//make title acceptable length write new title to xml
$title = _titleshort($x->{'offerdescription'},65-strlen($x->{'advertisername'}));
$title_out = str_replace("&","&amp;",$x->{'advertisername'}." - ".$title);
$x->addChild('title',$title_out);
//Get Key words  don't know how to use them yet.
$kws =_strip($title,TRUE);
$kw = implode(" ", $kws);
echo 'KEYWORDS: '.$kw."<br>";
if(isset($x->{'couponcode'})){
    echo "COUPON CODE: ".$x->{'couponcode'}."<br>";
    $x->addChild('type','coupon');
}
else{
    $x->addChild('type','offer');
}
//get categories aligned with ZUUZLO.com
$newcats = array();
foreach($x->categories->category as $cat){
    $newcats[] = _mapCat($cat->attributes()."");
    
}

$c=0;
foreach($newcats as $cats){
    $x->addChild("cat$c",$cats);
    echo $cats.'<br>';
    $c++;
}


//spin discription and rating
//spin meta description
$keyw = strtoupper($kw);
$vendname = $x->{'advertisername'};
$cat = $x->{'categories'}->{'category'};
$savings = SpinTax('${1|2|3}{0|1|2|3|4|5|6|7|8|9}');
$month = date('F');
$year = date('Y');
$fill = SpinTax("{Another great|An excellent|Another|Yet another excellent} {offer|coupon|coupon code} {brought to you|presented} by {ZUUZLO.com|ZUUZLO}. $keyw {is another|is yet another|is also a} {bargain|deal|good deal|good buy|great deal} {which can|that can|which could} {only|just|solely|simply|exclusively} {be found|be located} at $vendname. {For all|For any of} {your|the|the right} $cat {needs|requirements|ought to have|wants|necessities} {shop|buy|purchase} at $vendname {and|and also|as well as|and even} {find|discover|locate|uncover} all the {great deals|money saving deals|great bargains|bargains|cheap deals} {for|to get|just for} $cat at {ZUUZLO.com|ZUUZLO}. {Hurry|Race} and {get|purchase|find|buy} the {deals|offers|bargains|discounts|special deals|savings} {now|right now|today|right away}, $month $year {deals|offers|bargains|discounts|special deals|promotions} are {ending|coming to an end|discontinuing} {soon|quickly|shortly|before long}!");
$fill = str_replace("&","&amp;",$fill);
$x->addChild('fill',$fill);
//$desmeta = SpinTax("{Discounts|Special discounts|Reductions|Savings} {average|usually are|generally are} $savings on $cat with $vendname {coupons|coupon codes|discount codes|discount coupons|special discounts}. {Save|Pay less|Save money} {now|right now|today} at $vendname, $month $year {offers|deals|deals and offers} are expiring {soon|quickly|before long|very soon}.");  Good for store meta description
echo $fill." ".strlen($fill)."<br>";
//meta description
$desmeta = _metadeclng($x->{'offerdescription'}.  SpinTax(" {Save|Pay less|Save money} {now|right now|today} at $vendname, $month $year {offers|deals|deals and offers} are expiring {soon|quickly|before long|very soon}. {Discounts|Special discounts|Reductions|Savings} {average|usually are|generally are} $savings on $cat with $vendname {coupons|coupon codes|discount codes|discount coupons|special discounts}."),156);
$desmeta = str_replace("&","&amp;",$desmeta);
$x->addChild('meta',$desmeta);
echo "META: ".$desmeta." ".strlen($desmeta)."<br>";


//picture link
$src = $imglist[$x->{'advertiserid'}.""];
echo '<IMG src="'.$src.'" width="120"/>'; 
$x->addChild('imgsrc',str_replace("&","&amp;",$src));


echo $x->{'offerdescription'}."<br>";
echo $title_out." ".strlen($title_out)."<br>";
echo "__________________________<br>";       
        
   
}//end of foreach
if($pagenumber == '1'){ 
	echo 'hello <br />'; 
	$dom = new DOMDocument('1.0', 'utf-8');
	$dom->preserveWhiteSpace = false;
	$dom->formatOutput = true;
	$dom->loadXML($xml->asXML());
	//$dom->save('/home/kirk/http/simpleC/cj/cjSale'.$pagenumber.'.xml');
	$dom->save($path.$filePage);
	echo "wrote xml $pagenumber <br />";
	$xmlT = simplexml_load_file($path.$filePage);
}
else{
	
	$cn2 = $xml->link->count();
	$cn1 = $xmlT->link->count();
	echo $cn2." ".$cn1."<br />";
	foreach( $xml->link as $foo ) {
		//echo $foo."<br />";
		$new =	$xmlT->addChild( 'link' , $foo );	
			
	}
	$cn = $cn1 + $cn2;	
	$j = $cn1;
	do{
		foreach($xml->link[$j-($cn1)]->children() as $foo2){
		//echo $foo2."<br />";
		$data = str_replace("&","&amp;",$foo2);  //replace &
	   	$new = $xmlT->link[$j]->addchild($foo2->getName(), $data);
		}

		 ++$j;

	} while ($j < $cn);

}
++$pagenumber;
}while($pagenumber < ($pages+1));



$dom = new DOMDocument('1.0', 'utf-8');
$dom->preserveWhiteSpace = false;
$dom->formatOutput = true;
$dom->loadXML($xmlT->asXML());
//$dom->save('/home/kirk/http/simpleC/cj/cjSale'.$pagenumber.'.xml');
$dom->save($path.$fileOut);
echo "wrote xml";

//}while($pagenumber < ($pages+1));

//$returnXML = simplexml_load_string($curl_results);
//var_dump($returnXML);
?>

<?php  


function SpinTax($s) {
    preg_match('#{(.+?)}#is',$s,$m);
    if(empty($m)) return $s;

    $t = $m[1];

    if(strpos($t,'{')!==false){
            $t = substr($t, strrpos($t,'{') + 1);
    }

    $parts = explode("|", $t);
    $s = preg_replace("+{".preg_quote($t)."}+is", $parts[array_rand($parts)], $s, 1);

    return SpinTax($s);
}
?>
